const PDFDocument = require('pdfkit');

module.exports = async (req, res) => {
  cors(res);
  if (req.method === 'OPTIONS') return res.end();
  // demo 下载可不校验 token，如需限制可开启 auth

  res.statusCode = 200;
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Cache-Control', 'no-store');

  const title = (req.query && req.query.title) ? String(req.query.title) : 'AesNav Report';
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  doc.pipe(res);

  doc.fontSize(20).text(title, { align: 'left' });
  doc.moveDown();
  doc.fontSize(12).text('This is a demo PDF generated by the AesNav minimal API on Vercel.', { align: 'left' });
  doc.moveDown();
  doc.text('Disclaimer: For educational purposes only. Not medical advice. AI simulations are illustrative, not guaranteed outcomes.');
  doc.end();
};

function cors(res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');}
